"use server";

// Contact-scoped server actions.
//
// Canonical mutation recipe (see app/(app)/dashboard/actions.ts header).

import { Readable } from "node:stream";
import { revalidatePath } from "next/cache";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { drive, folderIdFromUrl } from "@/lib/drive";
import { writeAudit, writeActivity, partnerActor, agentActor } from "@/lib/audit";
import { normalizeDomain } from "@/lib/apollo";
import { assertNoNeedsInput } from "@/lib/no-hallucination";
import { generate } from "@/lib/ai";
import { formatCAD, formatDate } from "@/lib/format";
import type { InteractionType } from "@/lib/generated/prisma/enums";

// Accept only the schema's enum values — defense in depth on top of the
// <select> in LogInteractionModal.
const VALID_TYPES: InteractionType[] = ["call", "meeting", "email_sent", "email_received", "other"];

export async function logInteraction(
  contactId: string,
  input: {
    type: string; // underscored Prisma identifier (e.g. "email_sent")
    date: string; // ISO date "YYYY-MM-DD"
    summary: string;
    channel?: string;
  },
) {
  const session = await auth();
  if (!session?.user?.partnerId) throw new Error("Not authenticated");

  const summary = input.summary.trim();
  if (!summary) throw new Error("Summary is required");
  if (!VALID_TYPES.includes(input.type as InteractionType)) {
    throw new Error(`Invalid interaction type: ${input.type}`);
  }
  const date = new Date(input.date);
  if (Number.isNaN(date.getTime())) throw new Error(`Invalid date: ${input.date}`);

  const contact = await prisma.contact.findUnique({
    where: { id: contactId },
    select: { id: true, name: true, lastTouchAt: true },
  });
  if (!contact) throw new Error("Contact not found");

  const actor = partnerActor(
    session.user.partnerId,
    session.user.name ?? session.user.email ?? "Unknown",
  );
  const advanceTouch = date > contact.lastTouchAt;

  const interaction = await prisma.$transaction(async (tx) => {
    const created = await tx.interaction.create({
      data: {
        contactId,
        type: input.type as InteractionType,
        date,
        summary,
        channel: input.channel?.trim() || null,
        // Partner display name as the actor label — agents use "AGENT · CLAUDE".
        loggedBy: session.user.name ?? session.user.email ?? "Unknown",
      },
    });

    if (advanceTouch) {
      await tx.contact.update({
        where: { id: contactId },
        data: { lastTouchAt: date },
      });
    }

    await writeAudit(tx, {
      actor,
      action: "create.interaction",
      targetType: "Interaction",
      targetId: created.id,
      changes: {
        contactId,
        type: input.type,
        date: date.toISOString(),
        summaryLength: summary.length,
        advancedLastTouch: advanceTouch,
      },
    });

    await writeActivity(tx, {
      actor,
      type: "touch",
      target: contact.name,
      detail: summary.length > 120 ? summary.slice(0, 117) + "…" : summary,
      link: `/contacts/${contactId}`,
    });

    return created;
  });

  revalidatePath(`/contacts/${contactId}`);
  revalidatePath("/contacts");
  return { id: interaction.id };
}

// ──────────────────────────────────────────────────────────────────────
// Email draft / send — persistence recipe for the Draft email Quick Action.
//
// Both actions follow the canonical recipe end-to-end:
//   1. Validate body (no-hallucination gate)
//   2. Resolve scope (Client > Deal > orphan) for the Artifact + Drive folder
//   3. Upload body to Drive (Client folder if reachable, else Shared Drive root)
//   4. Inside a $transaction: Artifact row + (if sent) Interaction row +
//      advance Contact.lastTouchAt + writeAudit
//
// Drive upload happens BEFORE the transaction so a DB failure rolls back the
// DB writes; the orphan Drive file stays but its ID is in the audit row.
//
// The body is generated by generateEmailDraft() (below) via the draft-email
// skill, then editable by the partner in DraftEmailModal before save/send.
// generatedFromSkill is tagged "draft-email" on the Artifact accordingly.
// ──────────────────────────────────────────────────────────────────────

type EmailScope = {
  clientId: string | null;
  dealId: string | null;
  parentFolderId: string;
};

async function resolveEmailScope(contactId: string): Promise<{
  contact: { id: string; name: string; lastTouchAt: Date };
  scope: EmailScope;
}> {
  const contact = await prisma.contact.findUnique({
    where: { id: contactId },
    select: {
      id: true,
      name: true,
      lastTouchAt: true,
      primaryForClients: {
        select: { id: true, driveFolderUrl: true, updatedAt: true },
        orderBy: { updatedAt: "desc" },
        take: 1,
      },
      deals: {
        select: { id: true, updatedAt: true },
        orderBy: { updatedAt: "desc" },
        take: 1,
      },
    },
  });
  if (!contact) throw new Error("Contact not found");

  const sharedDriveFolderId = process.env.DRIVE_SHARED_DRIVE_FOLDER_ID;
  if (!sharedDriveFolderId) {
    throw new Error("DRIVE_SHARED_DRIVE_FOLDER_ID is not configured");
  }

  const client = contact.primaryForClients[0] ?? null;
  const deal = client ? null : contact.deals[0] ?? null;

  // Try the client's Drive folder; fall back to the Shared Drive root if the
  // URL doesn't parse (seed data uses placeholder URLs without /folders/<id>).
  let parentFolderId = sharedDriveFolderId;
  if (client) {
    try {
      parentFolderId = folderIdFromUrl(client.driveFolderUrl);
    } catch {
      // Placeholder URL — fall back to Shared Drive root and tag the artifact
      // (caller handles labeling).
    }
  }

  return {
    contact: { id: contact.id, name: contact.name, lastTouchAt: contact.lastTouchAt },
    scope: { clientId: client?.id ?? null, dealId: deal?.id ?? null, parentFolderId },
  };
}

async function uploadEmailToDrive(
  body: string,
  fileName: string,
  parentFolderId: string,
): Promise<{ fileId: string; webViewLink: string }> {
  const res = await drive.files.create({
    requestBody: {
      name: fileName,
      parents: [parentFolderId],
      mimeType: "text/markdown",
    },
    media: {
      mimeType: "text/markdown",
      body: Readable.from(body),
    },
    fields: "id, webViewLink",
    supportsAllDrives: true,
  });
  if (!res.data.id || !res.data.webViewLink) {
    throw new Error("Drive upload returned no ID");
  }
  return { fileId: res.data.id, webViewLink: res.data.webViewLink };
}

function summarizeBody(body: string): string {
  const firstLines = body
    .split("\n")
    .map((l) => l.trim())
    .filter(Boolean)
    .slice(0, 3)
    .join(" · ");
  return firstLines.length > 200 ? firstLines.slice(0, 197) + "…" : firstLines;
}

// ──────────────────────────────────────────────────────────────────────
// generateEmailDraft — the AI generation step for the Draft email Quick Action.
//
// Read/generate only: pulls firm context from Prisma, runs the draft-email skill
// through generate(), returns the body. Persistence (Artifact + Interaction +
// AuditLog) stays in saveEmailDraft / sendEmail. The returned body may contain
// [NEEDS INPUT: …] markers — the partner fills those before save/send, and the
// server-side gate (assertNoNeedsInput) blocks anything still flagged.
// ──────────────────────────────────────────────────────────────────────

export async function generateEmailDraft(
  contactId: string,
  input: {
    purpose: string;
    ask?: string;
    senderRole?: string;
    pricePoint?: string;
    timeline?: string;
    partnerName?: string;
  },
): Promise<{ body: string }> {
  const session = await auth();
  if (!session?.user?.partnerId) throw new Error("Not authenticated");

  const purpose = input.purpose.trim();
  if (!purpose) throw new Error("Purpose is required");

  const contact = await prisma.contact.findUnique({
    where: { id: contactId },
    select: {
      name: true,
      title: true,
      company: true,
      industry: true,
      notes: true,
      persona: true,
      communicationStyle: true,
      background: true,
      keyFacts: true,
      lastTouchAt: true,
      interactions: {
        orderBy: { date: "desc" },
        take: 5,
        select: { type: true, date: true, summary: true },
      },
      primaryForClients: {
        orderBy: { updatedAt: "desc" },
        take: 1,
        select: { company: true, status: true },
      },
      deals: {
        orderBy: { updatedAt: "desc" },
        take: 1,
        select: { stage: true, valueEstimate: true, closeTargetDate: true },
      },
    },
  });
  if (!contact) throw new Error("Contact not found");

  const client = contact.primaryForClients[0] ?? null;
  const deal = client ? null : contact.deals[0] ?? null;

  // ── Live context block (the "who this client is" half of the call) ──
  const contextLines: string[] = [
    "## Contact",
    `Name: ${contact.name}`,
    `Title: ${contact.title}`,
    `Company: ${contact.company}`,
    `Industry: ${contact.industry}`,
    `Last contact: ${formatDate(contact.lastTouchAt)}`,
  ];
  if (contact.persona) contextLines.push(`Persona: ${contact.persona}`);
  if (contact.communicationStyle) contextLines.push(`Communication style: ${contact.communicationStyle}`);
  if (contact.background) contextLines.push(`Background: ${contact.background}`);
  if (contact.keyFacts.length) contextLines.push(`Key facts: ${contact.keyFacts.join("; ")}`);
  if (contact.notes) contextLines.push(`Notes: ${contact.notes}`);

  if (client) {
    contextLines.push("", "## Relationship", `Active client — ${client.company} (status: ${client.status.replace("_", "-")}).`);
  } else if (deal) {
    contextLines.push(
      "",
      "## Relationship",
      `Open deal — stage: ${deal.stage}, est. value: ${formatCAD(deal.valueEstimate)}, target close: ${formatDate(deal.closeTargetDate)}.`,
    );
  } else {
    contextLines.push("", "## Relationship", "No active client or open deal — treat as an early / cold contact.");
  }

  if (contact.interactions.length) {
    contextLines.push("", "## Recent interactions (newest first)");
    for (const i of contact.interactions) {
      contextLines.push(`- ${formatDate(i.date)} · ${i.type.replace("_", "-")} — ${i.summary}`);
    }
  } else {
    contextLines.push("", "## Recent interactions", "None logged yet.");
  }

  const context = contextLines.join("\n");

  // ── Intake (the partner's instruction for THIS email) ──
  const intake = [
    "## This email",
    `Goal: ${purpose}`,
    `Specific ask / next step: ${input.ask?.trim() || "(not specified — propose one clear next step, or mark [NEEDS INPUT] if it depends on a fact you don't have)"}`,
    `Price / number to state: ${input.pricePoint?.trim() || "(none provided — do not invent one; use [NEEDS INPUT] if the email needs a number)"}`,
    `Timeline / date to commit: ${input.timeline?.trim() || "(none provided — do not invent one)"}`,
    `Sending partner: ${input.partnerName?.trim() || "[NEEDS INPUT: partner name]"}`,
    `Sending partner's role / sign-off: ${input.senderRole?.trim() || "(not given — omit a role line rather than guess)"}`,
  ].join("\n");

  const body = await generate({ skill: "draft-email", context, intake });
  return { body: body.trim() };
}

export async function saveEmailDraft(
  contactId: string,
  input: { body: string },
) {
  const session = await auth();
  if (!session?.user?.partnerId) throw new Error("Not authenticated");
  const partnerLabel = session.user.name ?? session.user.email ?? "Unknown";
  const actor = partnerActor(session.user.partnerId, partnerLabel);

  const body = input.body.trimEnd();
  if (!body.trim()) throw new Error("Email body is required");
  assertNoNeedsInput(body, "email body");

  const { contact, scope } = await resolveEmailScope(contactId);

  const today = new Date().toISOString().slice(0, 10);
  const fileName = `${today}-${contact.name.replace(/\s+/g, "-")}-email-draft.md`;
  const { fileId, webViewLink } = await uploadEmailToDrive(body, fileName, scope.parentFolderId);

  const artifact = await prisma.$transaction(async (tx) => {
    const created = await tx.artifact.create({
      data: {
        type: "email",
        title: `Email draft · ${contact.name} · ${today}`,
        driveUrl: webViewLink,
        fileName,
        createdBy: partnerLabel,
        generatedFromSkill: "draft-email",
        reviewStatus: "draft",
        clientId: scope.clientId,
        dealId: scope.dealId,
      },
    });

    await writeAudit(tx, {
      actor,
      action: "create.artifact.email.draft",
      targetType: "Artifact",
      targetId: created.id,
      changes: {
        contactId,
        scope: scope.clientId
          ? `client:${scope.clientId}`
          : scope.dealId
            ? `deal:${scope.dealId}`
            : "orphan",
        driveFileId: fileId,
        bodyLength: body.length,
      },
    });

    await writeActivity(tx, {
      actor,
      type: "doc",
      target: contact.name,
      detail: "Drafted email — awaiting review",
      link: `/contacts/${contactId}`,
    });

    return created;
  });

  revalidatePath(`/contacts/${contactId}`);
  if (scope.clientId) revalidatePath(`/clients/${scope.clientId}`);
  return { artifactId: artifact.id, driveUrl: webViewLink };
}

export async function sendEmail(
  contactId: string,
  input: { body: string },
) {
  const session = await auth();
  if (!session?.user?.partnerId) throw new Error("Not authenticated");
  const partnerLabel = session.user.name ?? session.user.email ?? "Unknown";
  const actor = partnerActor(session.user.partnerId, partnerLabel);

  const body = input.body.trimEnd();
  if (!body.trim()) throw new Error("Email body is required");
  assertNoNeedsInput(body, "email body");

  const { contact, scope } = await resolveEmailScope(contactId);

  const today = new Date().toISOString().slice(0, 10);
  const fileName = `${today}-${contact.name.replace(/\s+/g, "-")}-email-sent.md`;
  const { fileId, webViewLink } = await uploadEmailToDrive(body, fileName, scope.parentFolderId);

  const sentAt = new Date();
  const summary = summarizeBody(body);

  const result = await prisma.$transaction(async (tx) => {
    const artifact = await tx.artifact.create({
      data: {
        type: "email",
        title: `Email sent · ${contact.name} · ${today}`,
        driveUrl: webViewLink,
        fileName,
        createdBy: partnerLabel,
        generatedFromSkill: "draft-email",
        reviewStatus: "sent",
        clientId: scope.clientId,
        dealId: scope.dealId,
      },
    });

    const interaction = await tx.interaction.create({
      data: {
        contactId,
        type: "email_sent" as InteractionType,
        date: sentAt,
        summary,
        loggedBy: partnerLabel,
      },
    });

    if (sentAt > contact.lastTouchAt) {
      await tx.contact.update({
        where: { id: contactId },
        data: { lastTouchAt: sentAt },
      });
    }

    await writeAudit(tx, {
      actor,
      action: "create.artifact.email.sent",
      targetType: "Artifact",
      targetId: artifact.id,
      changes: {
        contactId,
        scope: scope.clientId
          ? `client:${scope.clientId}`
          : scope.dealId
            ? `deal:${scope.dealId}`
            : "orphan",
        driveFileId: fileId,
        bodyLength: body.length,
        interactionId: interaction.id,
        advancedLastTouch: sentAt > contact.lastTouchAt,
      },
    });

    await writeActivity(tx, {
      actor,
      type: "touch",
      target: contact.name,
      detail: `Sent email — ${summary}`,
      link: `/contacts/${contactId}`,
    });

    return { artifactId: artifact.id, interactionId: interaction.id };
  });

  revalidatePath(`/contacts/${contactId}`);
  if (scope.clientId) revalidatePath(`/clients/${scope.clientId}`);
  return { ...result, driveUrl: webViewLink };
}

// ──────────────────────────────────────────────────────────────────────
// AI enrich — the "Run an action" / "AI enrich" Quick Action.
//
// Two-step, propose-then-apply (the firm's non-destructive merge pattern):
//   generateEnrichment() reads the interaction log and PROPOSES additions
//   (returns structured items + conflicts — writes nothing).
//   applyEnrichment() takes the partner-approved additions and merges them
//   append-only into the Contact record (never overwrites an existing
//   single-value field; only appends new list items), then audits.
//
// Strictly log-based: Claude infers only from the record + logged history.
// No web access, no invented facts (enforced by the enrich-contact skill).
// ──────────────────────────────────────────────────────────────────────

// Fields the enrich-contact skill is allowed to touch. Split by shape so the
// merge knows append (lists) vs set-if-empty (scalars). The reach scalars
// (domain/linkedinUrl/location/timezone, D40) are web-enrich territory — the
// log-only skill doesn't propose them, but one allowlist serves both paths.
const ENRICH_LIST_FIELDS = ["keyFacts", "hobbies", "networkAffiliations"] as const;
const ENRICH_SCALAR_FIELDS = [
  "persona",
  "communicationStyle",
  "background",
  "domain",
  "linkedinUrl",
  "location",
  "timezone",
] as const;
type EnrichListField = (typeof ENRICH_LIST_FIELDS)[number];
type EnrichScalarField = (typeof ENRICH_SCALAR_FIELDS)[number];
type EnrichField = EnrichListField | EnrichScalarField;

export type EnrichAddition = { field: EnrichField; value: string };
export type EnrichConflict = {
  field: EnrichScalarField;
  existing: string;
  proposed: string;
  note?: string;
};

const ALL_ENRICH_FIELDS: string[] = [...ENRICH_LIST_FIELDS, ...ENRICH_SCALAR_FIELDS];

function isEnrichField(f: unknown): f is EnrichField {
  return typeof f === "string" && ALL_ENRICH_FIELDS.includes(f);
}

export async function generateEnrichment(
  contactId: string,
): Promise<{ additions: EnrichAddition[]; conflicts: EnrichConflict[] }> {
  const session = await auth();
  if (!session?.user?.partnerId) throw new Error("Not authenticated");

  const contact = await prisma.contact.findUnique({
    where: { id: contactId },
    select: {
      name: true,
      title: true,
      company: true,
      industry: true,
      notes: true,
      persona: true,
      communicationStyle: true,
      background: true,
      keyFacts: true,
      hobbies: true,
      networkAffiliations: true,
      interactions: {
        orderBy: { date: "desc" },
        take: 20,
        select: { type: true, date: true, summary: true },
      },
    },
  });
  if (!contact) throw new Error("Contact not found");

  if (contact.interactions.length === 0) {
    // Nothing to infer from — be honest rather than invent.
    return { additions: [], conflicts: [] };
  }

  const ctx: string[] = [
    "## Contact record (existing)",
    `Name: ${contact.name}`,
    `Title: ${contact.title}`,
    `Company: ${contact.company}`,
    `Industry: ${contact.industry}`,
    `Persona: ${contact.persona || "(empty)"}`,
    `Communication style: ${contact.communicationStyle || "(empty)"}`,
    `Background: ${contact.background || "(empty)"}`,
    `Key facts: ${contact.keyFacts.length ? contact.keyFacts.join("; ") : "(none)"}`,
    `Hobbies: ${contact.hobbies.length ? contact.hobbies.join("; ") : "(none)"}`,
    `Network affiliations: ${contact.networkAffiliations.length ? contact.networkAffiliations.join("; ") : "(none)"}`,
    `Notes: ${contact.notes || "(none)"}`,
    "",
    "## Logged interactions (newest first)",
  ];
  for (const i of contact.interactions) {
    ctx.push(`- ${formatDate(i.date)} · ${i.type.replace("_", "-")} — ${i.summary}`);
  }

  const raw = await generate({
    skill: "enrich-contact",
    context: ctx.join("\n"),
    intake:
      "Propose enrichment additions for this contact, inferring ONLY from the record and logged interactions above. Return the JSON object exactly as specified.",
  });

  // Parse the JSON object. Be tolerant of stray prose / code fences around it.
  const parsed = parseEnrichmentJSON(raw);
  return parsed;
}

// generateWebEnrichment — the web-mode sibling of generateEnrichment.
//
// Same propose-then-apply contract (returns additions + conflicts, writes
// nothing), but runs the enrich-contact-web skill with Anthropic's native
// web_search enabled. Claude looks up public, professional facts about the
// named person, citing sources inline; the partner approves, and the existing
// applyEnrichment() merges the chosen additions append-only. The skill — not
// this code — enforces "public + professional only, cite every fact, skip
// private/sensitive data, never the wrong person."
//
// Unlike the log-only path, we run even when there are no logged interactions:
// the web is the source here, not the log.
export async function generateWebEnrichment(
  contactId: string,
): Promise<{ additions: EnrichAddition[]; conflicts: EnrichConflict[] }> {
  const session = await auth();
  if (!session?.user?.partnerId) throw new Error("Not authenticated");

  const contact = await prisma.contact.findUnique({
    where: { id: contactId },
    select: {
      name: true,
      title: true,
      company: true,
      industry: true,
      notes: true,
      persona: true,
      communicationStyle: true,
      background: true,
      domain: true,
      linkedinUrl: true,
      location: true,
      timezone: true,
      keyFacts: true,
      hobbies: true,
      networkAffiliations: true,
    },
  });
  if (!contact) throw new Error("Contact not found");

  const ctx: string[] = [
    "## Contact record (existing)",
    `Name: ${contact.name}`,
    `Title: ${contact.title}`,
    `Company: ${contact.company}`,
    `Industry: ${contact.industry}`,
    `Persona: ${contact.persona || "(empty)"}`,
    `Communication style: ${contact.communicationStyle || "(empty)"}`,
    `Background: ${contact.background || "(empty)"}`,
    `Website (domain): ${contact.domain || "(empty)"}`,
    `LinkedIn: ${contact.linkedinUrl || "(empty)"}`,
    `Location: ${contact.location || "(empty)"}`,
    `Timezone: ${contact.timezone || "(empty)"}`,
    `Key facts: ${contact.keyFacts.length ? contact.keyFacts.join("; ") : "(none)"}`,
    `Hobbies: ${contact.hobbies.length ? contact.hobbies.join("; ") : "(none)"}`,
    `Network affiliations: ${contact.networkAffiliations.length ? contact.networkAffiliations.join("; ") : "(none)"}`,
    `Notes: ${contact.notes || "(none)"}`,
  ];

  const raw = await generate({
    skill: "enrich-contact-web",
    context: ctx.join("\n"),
    intake:
      "Use web search to find public, professional facts about this exact person (use their name, title, and company to disambiguate). Propose enrichment additions, citing a source for every fact. Return the JSON object exactly as specified.",
    webSearch: true,
    maxTokens: 2000,
  });

  return parseEnrichmentJSON(raw);
}

function parseEnrichmentJSON(raw: string): {
  additions: EnrichAddition[];
  conflicts: EnrichConflict[];
} {
  let text = raw.trim();
  // Strip a ```json fence if the model added one despite instructions.
  const fence = text.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (fence) text = fence[1].trim();
  // Otherwise slice to the outermost braces.
  if (!text.startsWith("{")) {
    const start = text.indexOf("{");
    const end = text.lastIndexOf("}");
    if (start !== -1 && end !== -1) text = text.slice(start, end + 1);
  }

  let obj: unknown;
  try {
    obj = JSON.parse(text);
  } catch {
    throw new Error("Enrichment returned malformed output — try again.");
  }
  const o = obj as { additions?: unknown; conflicts?: unknown };

  const additions: EnrichAddition[] = Array.isArray(o.additions)
    ? o.additions
        .filter(
          (a): a is { field: EnrichField; value: string } =>
            !!a &&
            typeof a === "object" &&
            isEnrichField((a as { field?: unknown }).field) &&
            typeof (a as { value?: unknown }).value === "string" &&
            (a as { value: string }).value.trim().length > 0,
        )
        .map((a) => ({ field: a.field, value: a.value.trim() }))
    : [];

  const isScalarField = (f: unknown): f is EnrichScalarField =>
    typeof f === "string" && (ENRICH_SCALAR_FIELDS as readonly string[]).includes(f);

  const conflicts: EnrichConflict[] = Array.isArray(o.conflicts)
    ? o.conflicts
        .filter(
          (c): c is EnrichConflict =>
            !!c &&
            typeof c === "object" &&
            isScalarField((c as { field?: unknown }).field) &&
            typeof (c as { existing?: unknown }).existing === "string" &&
            typeof (c as { proposed?: unknown }).proposed === "string",
        )
        .map((c) => ({
          field: c.field,
          existing: c.existing,
          proposed: c.proposed,
          note: typeof c.note === "string" ? c.note : undefined,
        }))
    : [];

  return { additions, conflicts };
}

export async function applyEnrichment(
  contactId: string,
  additions: EnrichAddition[],
) {
  const session = await auth();
  if (!session?.user?.partnerId) throw new Error("Not authenticated");
  const partnerLabel = session.user.name ?? session.user.email ?? "Unknown";

  const clean = (additions ?? []).filter((a) => isEnrichField(a?.field) && a.value?.trim());
  if (clean.length === 0) throw new Error("No additions to apply");

  const contact = await prisma.contact.findUnique({
    where: { id: contactId },
    select: {
      name: true,
      persona: true,
      communicationStyle: true,
      background: true,
      domain: true,
      linkedinUrl: true,
      location: true,
      timezone: true,
      keyFacts: true,
      hobbies: true,
      networkAffiliations: true,
    },
  });
  if (!contact) throw new Error("Contact not found");

  // Build the non-destructive update: append new list items; set scalar
  // fields ONLY if currently empty (never overwrite — that's a conflict the
  // partner resolves by hand).
  const data: Record<string, unknown> = {};
  const lists: Record<EnrichListField, string[]> = {
    keyFacts: [...contact.keyFacts],
    hobbies: [...contact.hobbies],
    networkAffiliations: [...contact.networkAffiliations],
  };
  const applied: EnrichAddition[] = [];
  const skipped: EnrichAddition[] = [];

  for (const a of clean) {
    if ((ENRICH_LIST_FIELDS as readonly string[]).includes(a.field)) {
      const f = a.field as EnrichListField;
      const exists = lists[f].some((v) => v.toLowerCase() === a.value.toLowerCase());
      if (!exists) {
        lists[f].push(a.value);
        applied.push(a);
      } else {
        skipped.push(a);
      }
    } else {
      const f = a.field as EnrichScalarField;
      // Proposed domains normalize to the bare host before the empty check —
      // same single source of truth as pipeline dedup (lib/apollo.ts).
      const value = f === "domain" ? normalizeDomain(a.value) : a.value;
      const current = contact[f];
      if (!value) {
        skipped.push(a);
      } else if (!current || !current.trim()) {
        data[f] = value;
        applied.push({ field: f, value });
      } else {
        // Already set — don't overwrite. Partner resolves conflicts manually.
        skipped.push(a);
      }
    }
  }

  for (const f of ENRICH_LIST_FIELDS) {
    if (lists[f].length !== contact[f].length) data[f] = lists[f];
  }

  if (applied.length === 0) {
    return { applied: 0, skipped: skipped.length };
  }

  data.enrichedAt = new Date();
  // The act of enriching is itself an AI surface, attributed to the skill.
  const aiActor = agentActor("enrich-contact");

  await prisma.$transaction(async (tx) => {
    await tx.contact.update({ where: { id: contactId }, data });

    await writeAudit(tx, {
      actor: aiActor,
      action: "update.contact.enrich",
      targetType: "Contact",
      targetId: contactId,
      changes: {
        approvedBy: partnerLabel,
        applied: applied.map((a) => ({ field: a.field, value: a.value })),
        skipped: skipped.length,
      },
    });

    await writeActivity(tx, {
      actor: aiActor,
      type: "ai",
      target: contact.name,
      detail: `Enriched record — ${applied.length} fact(s) added (approved by ${partnerLabel.split(" ")[0]})`,
      link: `/contacts/${contactId}`,
    });
  });

  revalidatePath(`/contacts/${contactId}`);
  return { applied: applied.length, skipped: skipped.length };
}

